{{- if .Values.redis.enableReadReplica }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-replica
  labels:
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/name: redis
    component: redis-replica
spec:
  replicas: {{ .Values.redis.readReplicas }}
  selector:
    matchLabels:
      app.kubernetes.io/instance: {{ .Release.Name }}
      component: redis-replica
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/name: redis
        component: redis-replica
    spec:
      containers:
      - name: redis
        image: redis:alpine
        ports:
        - containerPort: 6379
          name: tcp-redis
        command: ["redis-server"]
        args: ["--replicaof", "{{ .Release.Name }}-redis", "6379"]
{{- end }}