apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-vote
  labels:
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/name: vote
    component: vote
spec:
  type: NodePort
  ports:
  - name: http
    port: 8080
    targetPort: 80
    nodePort: 31000
  selector:
    app.kubernetes.io/instance: {{ .Release.Name }}
    component: vote